---
- name: download | Create directory {{ kafka_cache_download_path }}
  tags:
    - kafka_download
  ansible.builtin.file:
    path: "{{ kafka_cache_download_path }}"
    owner: root
    group: root
    mode: u=rw-x+X,g=r-x+X,o=r-x+X
    recurse: false
    state: directory

- name: download | Check if Kafka package checksum exists
  tags:
    - kafka_download
  ansible.builtin.stat:
    path: "{{ kafka_downloaded_checksum_file_path }}"
  register:
    kafka_package_checksum_stat

- name: download | GET Kafka package checksum
  tags:
    - kafka_download
  ansible.builtin.get_url:
    url: "{{ kafka_checksum_sha512_download_url }}"
    dest: "{{ kafka_downloaded_checksum_file_path }}"
    mode: u=rw-x,g=rw-x,o=r-x
    validate_certs: true
  register: kafka_package_archive_checksum_gpg
  when: (not kafka_package_checksum_stat.stat.exists)

- name: download | Slurp GPG package checksum
  ansible.builtin.slurp:
    src: "{{ kafka_downloaded_checksum_file_path }}"
  register: kafka_package_archive_checksum_gpg_slurped

- name: download | Convert Kafka package checksum
  tags:
    - kafka_download
  ansible.builtin.set_fact:
    kafka_package_archive_checksum_algorithm: sha512
    kafka_package_archive_checksum: "{{ kafka_package_archive_checksum_gpg_slurped.content | b64decode | ansible.builtin.regex_replace('(.+\\:)|([\\ \n])', '') | lower }}"
  failed_when: >-
    kafka_package_archive_checksum_algorithm is not defined
    or kafka_package_archive_checksum is not defined

- name: download | GET Kafka package
  tags:
    - kafka_download
  ansible.builtin.get_url:
    url: "{{ kafka_package_download_url }}"
    dest: "{{ kafka_downloaded_package_file_path }}"
    force: false
    checksum: "{{ kafka_package_archive_checksum_algorithm }}:{{ kafka_package_archive_checksum }}"
    mode: u=rw-x,g=rw-x,o=r-x
    validate_certs: true
...
