---
kafka_package_download_url: https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
kafka_checksum_sha512_download_url: "{{ kafka_package_download_url }}.sha512"

kafka_downloaded_checksum_file_path: "{{ kafka_cache_download_path }}/{{ kafka_checksum_sha512_download_url | ansible.builtin.basename }}"
kafka_downloaded_package_file_path: "{{ kafka_cache_download_path }}/{{ kafka_package_download_url | ansible.builtin.basename }}"

kafka_config_cluster_id_file_path: "{{ kafka_installation_prefix }}/CLUSTER_ID"

kafka_config_dir_path: "/etc/kafka"
