---
- name: Format Kafka log storage
  ansible.builtin.import_tasks:
    file: kafka_storage_format.yml

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
    no_block: false
    scope: system

- name: Restart kafka
  ansible.builtin.systemd_service:
    no_block: false
    scope: system
    name: kafka
    state: restarted
...
